---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
    driver_config:
      network:
      -  ["private_network", {ip: "33.33.33.10"}]

suites:
  - name: default
    run_list:
      - recipe[hello::default]
    attributes:
